"""empty message

Revision ID: 9ecb1f6bbdd8
Revises: 2465ea54a5f9
Create Date: 2024-04-25 14:43:51.280023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecb1f6bbdd8'
down_revision = '2465ea54a5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_buyer', schema=None) as batch_op:
        batch_op.alter_column('token_exp',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=datetime.timezone.utc),
               existing_nullable=True)
        batch_op.drop_constraint('user_buyer_token_exp_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_buyer', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_buyer_token_exp_key', ['token_exp'])
        batch_op.alter_column('token_exp',
               existing_type=sa.DateTime(timezone=datetime.timezone.utc),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
